### ISSUE TITLE
Only one message at a time

### ISSUE THREAD

**Issue by tomexx** [keen-on-design/vue-flash-message#11]
Is it possible to show only one message at a time? Or maybe to invalidate previous messages when spawning a new one? Thanks!

**Comment by keen-on-design** [comment]
There is no straightforward solution but you can use 
```getStorage()``` to gain access to a full list of messages and then perform a ```destroy()``` on old messages if a new one overrides previous. Or you can add some logics above to prevent new messages if storage is not empty (thats your code that emits flashes :)
