### ISSUE TITLE
Runtime Error: You are using the runtime-only build of Vue where the template compiler is not available.

### ISSUE THREAD

**Issue by theironcook** [keen-on-design/vue-flash-message#14]
Hi,
I'm getting the following error in chrome when I try to use the vue-flash-message:

main.ts:23 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <FlashMessage>
       <App> at src\App.vue
         <Root>

I'm running the project in development mode with the vue-cli.  It's a brand new project.  I'm using Typescript.

Here are few relevant code snippets.
main.ts
import Vue from 'vue'
import VueFlashMessage from 'vue-flash-message';
Vue.use(VueFlashMessage);

App.vue
<template>
  <div id="app">
    <flash-message></flash-message>
  </div>
</template>

I'm pretty sure I need to use a different version of Vue than what I'm including via import Vue from 'vue' but I can't figure out how to make things work.

**Comment by theironcook** [comment]
I figured it out - I needed to add runtimeCompiler: true in my vue.config.js file like this:

const vueConfig = {
  runtimeCompiler: true
}

**Comment by acrolink** [comment]
@theironcook Thank you very much for sharing the solution.
