### ISSUE TITLE
Is there a way to insert a router link to the message?

### ISSUE THREAD

**Issue by aygee** [keen-on-design/vue-flash-message#15]
I tried 

`this.info('Please go to <router-link to="/">here</router-link>')
`

But it doesn't work for obvious reason that it's not going to be compiled. It can work using Dynamic Component, but it requires a change in the implementation. Is there a way to make this happen without having to change the source code?

If not, should this become a feature? I'm happy to try to get it working and create a PR.

Thanks,

**Comment by keen-on-design** [comment]
You can not add router link directly as message contents is not compiled as a vue template. But a message accepts an html, not plain text. So basically you can manually resolve it using vue-router api (i guess). If you have some ideas on a better solution, please make a PR, thank you!
