### ISSUE TITLE
Precompile default template to remove dependency on runtime compiler

### ISSUE THREAD

**Issue by doits** [keen-on-design/vue-flash-message#16]
By providing the default template as a string, it is not precompiled even when only the default template is used. You need to include the runtime compile in your vue app just for the plugin.

Why not precompile the default template? E.g. make a `.vue` component with the default template that can be precompiled (by the app including it) and only use a dynamic string template when explicitly needed.

What do you think?

**Comment by keen-on-design** [comment]
I apologise for such a bad timing:(. In 0.7.0 template is made as a render-function. Currently re-definition of template is not supported as it is not a commonly used function anyways.

**Comment by keen-on-design** [comment]
I am closing this issue for now

**Comment by vsjov** [comment]
Oh this is bad. We have specifically used your plugin in Open Law Library because we wanted to customize template to better suit our design. Are you planning to introduce templates again, or is this a done deal?

**Comment by keen-on-design** [comment]
@Vlasterx ok, I’ll try to bring back templates again. Need to find a good way of combining precompiled template and a custom template feature. Please, create a new issue on that. If you have any ideas, please suggest:)

**Comment by vsjov** [comment]
Will do, gladly. Thanks!

**Comment by vsjov** [comment]
Here is the new issue #23
