### ISSUE TITLE
Shortcuts: Name conflict with vue 2.5.17

### ISSUE THREAD

**Issue by falue** [keen-on-design/vue-flash-message#18]
With maybe the latest release of vue 2.5.17 there seems to be some conflicts due to the shortcuts named 'success' and 'error' – same as the methods in vue.
Vue thows these errors for each v-input:

```
[Vue warn]: Method "success" has already been defined as a prop.
```
```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "success"
```

Only way around seems to be to set `createShortcuts: false` in `main.js` which works as expected:
```
Vue.use(VueFlashMessage,
  {
    messageOptions: {
      timeout: 3000,
      ...
    },
    template,
    createShortcuts: false  }
);
```
Thanks!

**Comment by keen-on-design** [comment]
Fixed in 0.7.0. Methods were renamed to flashSuccess etc. Please upgrade and enjoy!:)
