### ISSUE TITLE
import VueFlashMessage from '../src' seems does NOT work

### ISSUE THREAD

**Issue by Rolanddoda** [keen-on-design/vue-flash-message#2]
I followed the instuctions but i got the error displayed in picture 
![image](https://user-images.githubusercontent.com/18482346/35782352-e2ee416c-09f6-11e8-895e-eff2a1a49593.png)

**Comment by Rolanddoda** [comment]
I fix it by write instead of :
`import VueFlashMessage from '../src'`
writing this:
`import VueFlashMessage from 'vue-flash-message'`

Anyway besides that the need more changes

**Comment by keen-on-design** [comment]
Oh, wow. Sorry, my bad). I have no idea why I made such a stupid mistake:)). Of course it should be  ```import VueFlashMessage from 'vue-flash-message'```
