### ISSUE TITLE
Template support

### ISSUE THREAD

**Issue by vsjov** [keen-on-design/vue-flash-message#23]
# Template support
First of all, thanks for creating this plugin. I am web designer for [Open Law Library](http://www.openlawlib.org/). We have selected to use it with our project since it proved to be best for our needs, especially because it had the possibility for custom templates and styles. With a bit of customization, we were able to achieve something like this

![oll-messages](https://user-images.githubusercontent.com/2601074/50280330-7ea0be00-044c-11e9-90b5-23a46bd16f47.png)

## Our template 
Our template looked like this one:

```js
const defaultTemplate = `
<transition-group
	:name="transitionName"
	:class="outerClass"
	tag="div"
>
	<div
		v-for="(message, index) in storage"
		:key="index"
		:class="cssClasses(index) + ' flash-message'"
		:aria-labelledby="'flash_' + index"
		tabindex="0"
		role="alert"
		aria-live="polite"
		aria-atomic="true"
		@mouseover="onMouseOver(index)"
		@mouseleave="onMouseOut(index)"
		@keypress.enter="destroyFlash(index)"
		@keypress.space="destroyFlash(index)"
	>
		<div class="flash-message__icon">
			<span v-if="cssClasses(index) === 'info'" class="icon icon-info" aria-label="Information icon"></span>
			<span v-else-if="cssClasses(index) === 'success'" class="icon icon-ok-o" aria-label="Success icon"></span>
			<span v-else-if="cssClasses(index) === 'warning'" class="icon icon-exclamation" aria-label="Warning icon"></span>
			<span v-else-if="cssClasses(index) === 'error'" class="icon icon-exclamation-triangle" aria-label="Error icon"></span>
			<span v-else class="icon icon-oll"></span>
		</div>
		<div :id="'flash_' + index" class="flash-message__content" v-html="message.content"></div>
		<div class="flash-message__close">
			<button v-if="!message.options.important"
				type="button"
				class="button button--icon button--transparent"
				data-dismiss="alert"
				aria-label="Close message"
				@click.stop.prevent="destroyFlash(index)"
			>
				<span class="icon icon-x" aria-label="Close dialog"></span>
			</button>
		</div>
	</div>
</transition-group>
`;
```

Styles and [icons](https://github.com/Bitersen/biticons) were custom made and were included in the main SCSS file. 

Is it possible to create separate `.vue` component with message template, scripts and styles, which can be reused every time messages are called? I guess that templating would be much easier in this way.

**Comment by tsaquet** [comment]
Hello ! That is something I really would like to do. Did you find a workaround to be able to provide a template ?

**Comment by vsjov** [comment]
I don't remember why this didn't work for us in the end, but we moved on to another library [Vue Toasted](https://shakee93.github.io/vue-toasted/) where we achieved the result from the image.

**Comment by Vlasterx** [comment]
I don't remember why this didn't work for us in the end, but we moved on to another library [Vue Toasted](https://shakee93.github.io/vue-toasted/) where we achieved the result from the image.
