### ISSUE TITLE
Messages appear at top of page not top of screen

### ISSUE THREAD

**Issue by ant-g** [keen-on-design/vue-flash-message#25]
My flash messages are appearing Absolute to the top of the page, so they are hidden if the page is scrolled, these should appear absolute to top of Screen so that they always display.

Is there a way to make these 'fixed' ?  Have I missed a setting somewhere?

UPDATE: yes I have, I can now see that I have control over the class where it is inserted in the template, so this issue can be closed.  thnx

**Comment by AndreiD** [comment]
set z-index higher in css maybe ?
