### ISSUE TITLE
Add an ability to set default options

### ISSUE THREAD

**Issue by desecho** [keen-on-design/vue-flash-message#4]
I want to always have `{timeout: 1500}` set as options but I have to put it every time I call `flash()`

**Comment by toriyasu** [comment]
@keen-on-design  @desecho 
I send this PR :)
plz check it~ 

https://github.com/keen-on-design/vue-flash-message/pull/7

**Comment by iohansson** [comment]
@desecho @toriyasu issue resolved in 0.5.0. Check out the docs.

**Comment by toriyasu** [comment]
@iohansson thx !!
